version: '3.9'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python /code/manage.py migrate --noinput && gunicorn backend.wsgi --bind 0.0.0.0:8000 -w 4"
    volumes:
      - .:/code
    networks:
      - nginx_network

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network

  # celery:
  #   build: .
  #   command: celery -A backend.celery worker -l INFO
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis
  #     - mongo
  #   networks: 
  #     - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge