version: '3.9'

services:  
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python /code/manage.py migrate --noinput && gunicorn backend.wsgi --bind 0.0.0.0:8000 -w 4"
    volumes:
      - .:/code
    networks:
      - nginx_network

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network

  telegrambot:
    build: ./telegrambot
    command: sh -c "python bot_tasks.py"
    # depends_on:
    #   - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge