version: '3.9'

services:  
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - network

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python /code/manage.py migrate --noinput && gunicorn backend.wsgi --bind 0.0.0.0:8000 -w 4"
    volumes:
      - .:/code
    networks:
      - network
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - .env

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - db
    networks:
      - network

  # telegrambot:
  #   build: .
  #   command: python run_bot.py
  #   depends_on:
  #     - web
  #     - db
  #   networks:
  #     - network
  #   env_file:
  #     - .env

networks:
  network:
    driver: bridge

volumes:
  db: