version: '3.9'

services:
  db:
    image: postgres
    networks: 
      - nginx_network

  redis:
    image: "redis:alpine"
    networks:
      - nginx_network

  mongo:
    image: mongo:3
    container_name: mongo
    # volumes:
    #   - .././data/mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - nginx_network

  web:
    build: .
    command: python3 /code/manage.py migrate --noinput && gunicorn backend.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
      - redis
      - mongo
    networks:
      - nginx_network

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - db
      - redis
      - mongo
    networks:
      - nginx_network

  # celery:
  #   build: .
  #   command: celery -A backend.celery worker -l INFO
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis
  #     - mongo
  #   networks: 
  #     - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge